add ShoppingCart and CartItem models
VictoriaMrkvch/book-store pull request #10
Opened 2024-01-23 12:23 UTC by VictoriaMrkvch

2024-01-23 16:24 UTC, okuzan requested changes
Good job

2024-01-23 16:24 UTC, okuzan commented on src/main/java/book/store/intro/model/CartItem.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE cart_items SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2024-01-23 16:24 UTC, okuzan commented on src/main/java/book/store/intro/service/shoppingcart/CartItemServiceImpl.java
> +                                + requestDto.getBookId())), getShoppingCart());
extract to a local variable to make more readable

2024-01-24 19:13 UTC, olekskov approved these changes

2024-01-25 09:54 UTC, merged