add README file
VictoriaMrkvch/book-store pull request #14
Opened 2024-02-15 18:41 UTC by VictoriaMrkvch

2024-02-15 19:55 UTC, okuzan requested changes

2024-02-15 19:55 UTC, okuzan commented on README.md
> +7. For testing using Postman, open the Postman web or desktop client and enter the URL `http://localhost:8088/api/{endpoint}`.
8088 or 8082?
or just use some <PORT> placeholder and mention that it can be changes in properties

2024-02-15 19:55 UTC, okuzan commented on README.md
> +5. MySQL
include versions for mysql, spring boot, java

2024-02-16 11:54 UTC, olekskov approved these changes

2024-02-16 12:21 UTC, merged